@startuml
left to right direction
skinparam packageStyle rectangle

actor "User" as User

rectangle "Storage Logging" {
    usecase "Add Storage Item" as UC_Add
    usecase "View Storage Log" as UC_List
    usecase "Update Storage Item" as UC_Update
    usecase "Delete Storage Item" as UC_Delete

    usecase "Check Low Stock Status" as UC_Check
    usecase "Calculate Remaining Weight" as UC_CalcWeight
}

User --> UC_Add
User --> UC_List
User --> UC_Update
User --> UC_Delete

UC_List ..> UC_Check : <<include>>
UC_List ..> UC_CalcWeight : <<include>>
UC_Update ..> UC_CalcWeight : <<include>>

@enduml