### Register and capture tokens
# @name register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "test@test.test",
  "password": "testtesttest"
}

> {%
    const cookieHeaders = response.headers.valuesOf("Set-Cookie");

    for (let i = 0; i < cookieHeaders.length; i++) {
        const header = cookieHeaders[i];

        // Look for access_token
        if (header.includes("access_token=")) {
            const token = header.split(';')[0].split('=')[1];
            client.global.set("accessToken", token);
            client.log("Access Token captured: " + token);
        }

        // Look for refresh_token
        if (header.includes("refresh_token=")) {
            const token = header.split(';')[0].split('=')[1];
            client.global.set("refreshToken", token);
        }
    }
%}

### Login and capture tokens
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

> {%
    const cookieHeaders = response.headers.valuesOf("Set-Cookie");

    for (let i = 0; i < cookieHeaders.length; i++) {
        const header = cookieHeaders[i];

        // Look for access_token
        if (header.includes("access_token=")) {
            const token = header.split(';')[0].split('=')[1];
            client.global.set("accessToken", token);
            client.log("Access Token captured: " + token);
        }

        // Look for refresh_token
        if (header.includes("refresh_token=")) {
            const token = header.split(';')[0].split('=')[1];
            client.global.set("refreshToken", token);
        }
    }
%}

### Logout
# @name logout
POST {{baseUrl}}/api/auth/logout
Content-Type: application/json
Cookie: accessToken={{accessToken}}

> {%
    const cookieHeaders = response.headers.valuesOf("Set-Cookie");

    for (let i = 0; i < cookieHeaders.length; i++) {
        const header = cookieHeaders[i];

        // Look for access_token
        if (header.includes("access_token=")) {
            const token = header.split(';')[0].split('=')[1];
            client.global.set("accessToken", token);
            client.log("Access Token captured: " + token);
        }

        // Look for refresh_token
        if (header.includes("refresh_token=")) {
            const token = header.split(';')[0].split('=')[1];
            client.global.set("refreshToken", token);
        }
    }
 %}

### Refresh Token
# @name refresh
POST {{baseUrl}}/api/auth/refresh
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "refreshToken": "{{refreshToken}}"
}
