### Get all meals
GET {{baseUrl}}/api/meals?date=2025-11-17
Cookie: access_token={{accessToken}}

### Create a meal
POST {{baseUrl}}/api/meals
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "name": "New Meal 1",
  "weight": 200.0,
  "nutrition": {
    "protein": 30.0,
    "carbs": 0.0,
    "fat": 5.0,
    "kcal": 165.0
  },
  "consumedAt": "2025-11-17T12:00:00Z"
}

### Create a meal with storage
POST {{baseUrl}}/api/meals
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "name": "New Meal 2",
  "weight": 200.0,
  "nutrition": {
    "protein": 30.0,
    "carbs": 0.0,
    "fat": 5.0,
    "kcal": 165.0
  },
  "consumedAt": "2025-11-17T12:00:00Z",
  "storageId": "e9014365-839a-470d-9023-f0161f866284"
}

### Delete a meal
DELETE {{baseUrl}}/api/meals/{{mealId}}
Cookie: access_token={{accessToken}}

### Update a meal
PUT {{baseUrl}}/api/meals/be814864-a552-47ba-8bf0-d31341548c54
Content-Type: application/json
Cookie: access_token={{accessToken}}

{
  "name": "Test",
  "weight": 150,
  "nutrition": {
    "protein": 30.0,
    "carbs": 150.0,
    "fat": 0.0,
    "kcal": 35.0
  },
  "consumedAt": "2025-11-17T12:00:00Z",
  "storageId": "e9014365-839a-470d-9023-f0161f866284"
}