package com.automagic.foodtracker.service;

import com.automagic.foodtracker.entity.Meal;
import com.automagic.foodtracker.entity.Nutrition;
import com.automagic.foodtracker.entity.Storage;
import com.automagic.foodtracker.repository.meal.MealRepository;
import com.automagic.foodtracker.repository.storage.StorageRepository;
import com.automagic.foodtracker.service.meal.MealService;
import com.automagic.foodtracker.service.meal.MealServiceImpl;
import com.automagic.foodtracker.service.storage.StorageService;
import com.automagic.foodtracker.service.storage.StorageServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.MongoDBContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.time.Instant;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@Testcontainers
@DataMongoTest
@Import({ StorageServiceImpl.class, MealServiceImpl.class})
public class MealServiceImplTest {
    @Container
    static MongoDBContainer mongoContainer = new MongoDBContainer("mongo:6.0");

    @Autowired
    private MealRepository mealRepository;
    @Autowired
    private MealService mealService;
    @Autowired
    private StorageRepository storageRepository;
    @Autowired
    private StorageService storageService;

    @DynamicPropertySource
    static void setProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.data.mongodb.uri", mongoContainer::getReplicaSetUrl);
    }

    @BeforeEach
    void cleanDb() {
        mealRepository.deleteAll();
        storageRepository.deleteAll();
    }

    @Test
    void testRegisterMealSavesMealCorrectly() {
        final Instant fixedTime = Instant.parse("2022-01-01T00:00:00.00Z");

        Meal newMeal = new Meal();

        newMeal.setUserId("user123");
        newMeal.setName("Chicken");
        newMeal.setWeight(200.0);
        newMeal.setNutrition(new Nutrition(10.0, 20.0, 5.0, 150.0));
        newMeal.setConsumedAt(fixedTime);

        Meal registeredMeal = mealService.registerMeal(newMeal);

        assertThat(registeredMeal).isNotNull();
        assertThat(registeredMeal.getId()).as("ID should be generated by MongoDB").isNotBlank();
        assertThat(registeredMeal.getConsumedAt()).isEqualTo(fixedTime);

        Optional<Meal> mealFromDb = mealRepository.findById(registeredMeal.getId());

        assertThat(mealFromDb).as("Meal should be retrievable from database").isPresent();
        assertThat(mealFromDb.get().getUserId()).isEqualTo("user123");
        assertThat(mealFromDb.get().getName()).isEqualTo("Chicken");
        assertThat(mealFromDb.get().getWeight()).isEqualTo(200.0);
        assertThat(mealFromDb.get().getNutrition().protein()).isEqualTo(10.0);
        assertThat(mealFromDb.get().getConsumedAt()).isEqualTo(fixedTime);
    }

}
