package com.automagic.foodtracker.service;

import com.automagic.foodtracker.entity.Meal;
import com.automagic.foodtracker.entity.Nutrition;
import com.automagic.foodtracker.repository.meal.MealRepository;
import com.automagic.foodtracker.repository.storage.StorageRepository;
import com.automagic.foodtracker.service.meal.MealService;
import com.automagic.foodtracker.service.meal.MealServiceImpl;
import com.automagic.foodtracker.service.storage.StorageService;
import com.automagic.foodtracker.service.storage.StorageServiceImpl;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.time.Instant;
import java.util.Collection;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@Testcontainers
@DataJpaTest
@Import({ StorageServiceImpl.class, MealServiceImpl.class})
public class MealServiceImplTest {
    @Container
    static PostgreSQLContainer<?> postgresContainer = new PostgreSQLContainer<>("postgres:15")
            .withDatabaseName("foodtracker")
            .withUsername("user")
            .withPassword("password");

    @Autowired
    private MealRepository mealRepository;
    @Autowired
    private MealService mealService;
    @Autowired
    private StorageRepository storageRepository;
    @Autowired
    private StorageService storageService;

    @DynamicPropertySource
    static void setProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgresContainer::getJdbcUrl);
        registry.add("spring.datasource.username", postgresContainer::getUsername);
        registry.add("spring.datasource.password", postgresContainer::getPassword);
    }

    @BeforeEach
    void cleanDb() {
        mealRepository.deleteAll();
        storageRepository.deleteAll();
    }

    //Helper Methods
    private Meal createTestMeal(String userId, String name, double weight, Nutrition nutrition, Instant consumedAt) {
        Meal meal = new Meal();
        meal.setUserId(userId);
        meal.setName(name);
        meal.setWeight(weight);
        meal.setNutrition(nutrition);
        meal.setConsumedAt(consumedAt);
        return meal;
    }

    // Tests
    @Test
    @DisplayName("registerMeal() should save meal to the database")
    void registerMealSavesMealCorrectly() {
        final Instant fixedTime = Instant.parse("2022-01-01T00:00:00.00Z");
        Meal newMeal = createTestMeal(
                "user123",
                "Chicken",
                200.0,
                new Nutrition(10.0, 20.0, 5.0, 150.0),
                fixedTime
        );

        Meal registeredMeal = mealService.registerMeal(newMeal);

        assertThat(registeredMeal).isNotNull();
        assertThat(registeredMeal.getId()).as("ID should be generated by UUID").isNotBlank();
        assertThat(registeredMeal.getConsumedAt()).isEqualTo(fixedTime);

        Optional<Meal> mealFromDb = mealRepository.findById(registeredMeal.getId());

        assertThat(mealFromDb).as("Meal should be retrievable from database").isPresent();
        assertThat(mealFromDb.get().getUserId()).isEqualTo("user123");
        assertThat(mealFromDb.get().getName()).isEqualTo("Chicken");
        assertThat(mealFromDb.get().getWeight()).isEqualTo(200.0);
        assertThat(mealFromDb.get().getNutrition().protein()).isEqualTo(10.0);
        assertThat(mealFromDb.get().getConsumedAt()).isEqualTo(fixedTime);
    }

    @Test
    @DisplayName("getAllMeals() should return all meals for specific user")
    void getMealByUserIdRetrievesOnlyCorrectUserMeals() {
        final Instant fixedTime1 = Instant.parse("2022-01-01T00:00:00.00Z");
        final Instant fixedTime2 = Instant.parse("2022-01-01T15:00:00.00Z");
        final Instant consumedTime1 = Instant.parse("2022-01-01T11:00:00.00Z");
        final Instant consumedTime2 = Instant.parse("2022-01-01T13:00:00.00Z");

        Meal newMeal1 = createTestMeal(
                "user456",
                "Pizza",
                150.0,
                new Nutrition(10.0, 20.0, 5.0, 150.0),
                consumedTime1
        );

        Meal newMeal2 = createTestMeal(
                "user456",
                "Hamburger",
                150.0,
                new Nutrition(10.0, 20.0, 5.0, 150.0),
                consumedTime2
        );

        Meal newMeal3 = createTestMeal(
                "user654",
                "Not Pizza",
                1000.0,
                new Nutrition(100.0, 200.0, 50.0, 1500.0),
                fixedTime2
        );

        Meal registeredMeal1 = mealService.registerMeal(newMeal1);
        Meal registeredMeal2 = mealService.registerMeal(newMeal2);
        Meal decoyMeal = mealService.registerMeal(newMeal3);

        Collection<Meal> mealsFromDb = mealService.getAllMeals(newMeal1.getUserId(), fixedTime1, fixedTime2);

        assertThat(mealsFromDb).as("Meals for specific user should only be retrieved").hasSize(2);
        assertThat(mealsFromDb)
                .extracting(Meal::getId)
                .containsExactlyInAnyOrder(registeredMeal1.getId(), registeredMeal2.getId());

        assertThat(mealsFromDb)
                .extracting(Meal::getUserId)
                .doesNotContain("user654");
    }

    @Test
    @DisplayName("getAllMeals() should return an empty array if no meals exist for time period")
    void getMealByUserIdRetrievesEmptyArrayWhenNoMealsExist() {
        final Instant fixedTime1 = Instant.parse("2022-02-01T00:00:00.00Z");
        final Instant fixedTime2 = Instant.parse("2022-02-01T23:59:00.00Z");
        final Instant consumedTime = Instant.parse("2022-01-01T11:00:00.00Z");

        Meal newMeal = createTestMeal("user456", "Pizza", 150.0, new Nutrition(10.0, 20.0, 5.0, 150.0), consumedTime);

        Meal registeredMeal = mealService.registerMeal(newMeal);
        Collection<Meal> allMealsFromDb = mealRepository.findAll();
        assertThat(allMealsFromDb).as("Meals should be present in database").isNotEmpty();

        Collection<Meal> mealsFromDb = mealService.getAllMeals("user456", fixedTime1, fixedTime2);
        assertThat(mealsFromDb).as("Meals for specific user should only be retrieved").isEmpty();
    }


    @Test
    @DisplayName("getDailyNutrition() should return summed nutrition values for the given day")
    void getDailyNutritionReturnsSummedNutritionForDay() {
        final Instant fixedTime1 = Instant.parse("2022-01-01T00:00:00.00Z");
        final Instant fixedTime2 = Instant.parse("2022-01-01T23:59:59.00Z");
        final Instant consumedTime1 = Instant.parse("2022-01-01T11:00:00.00Z");
        final Instant consumedTime2 = Instant.parse("2022-01-01T13:00:00.00Z");

        Meal newMeal1 = createTestMeal("user456", "Pizza", 150.0, new Nutrition(10.0, 20.0, 5.0, 150.0), consumedTime1);
        Meal newMeal2 = createTestMeal("user456", "Pizza", 150.0, new Nutrition(10.0, 20.0, 5.0, 150.0), consumedTime2);

        Meal registeredMeal1 = mealService.registerMeal(newMeal1);
        Meal registeredMeal2 = mealService.registerMeal(newMeal2);

        Nutrition dailyNutritionSum = mealService.getDailyNutrition("user456", fixedTime1, fixedTime2);

        assertThat(dailyNutritionSum)
                .extracting(Nutrition::protein,
                        Nutrition::carbs,
                        Nutrition::fat,
                        Nutrition::kcal
                )
                .containsExactly(20.0, 40.0, 10.0, 300.0);
    }

    @Test
    @DisplayName("getDailyNutrition() should return zero nutrition values for the given day if no meals exist")
    void getDailyNutritionReturnsZeroNutritionForDayWhenNoMealsExist() {
        final Instant fixedTime1 = Instant.parse("2022-02-01T00:00:00.00Z");
        final Instant fixedTime2 = Instant.parse("2022-02-01T23:59:59.00Z");

        Nutrition dailyNutritionSum = mealService.getDailyNutrition("user456", fixedTime1, fixedTime2);

        assertThat(dailyNutritionSum).isEqualTo(new Nutrition(0.0, 0.0, 0.0, 0.0));
    }

}
